### ISSUE TITLE
 Stopped working with new snapshots release

### ISSUE THREAD

**Issue by sojusnik** [shivams/zim-tag-autocompletion#2] opened 2021-09-18 09:55 UTC
As with `0.74.0-SNAPSHOT-t202109171459~ubuntu21.04.1` from [Jaap's PPA](https://launchpad.net/~jaap.karssenberg/+archive/ubuntu/zim-snapshots?field.series_filter=hirsute) the tag autocompletion plugin stopped working.

Can you have a look on this?

**Comment by shivams** [comment] 2021-09-18 11:53
Thanks for reporting this @sojusnik. Will have a look at it in the coming week.

**Comment by fmos** [comment] 2021-11-25 11:14
I can confirm this issue with the present Zim release 0.74.2

The issue appears to be related to #3. The upstream method zim.gui.widgets.Window.show_all() crashes. Perhaps it is not intended to call this function directly? 

Or perhaps upstream needs to be fixed to properly initialize Window.uistate in [`Window.__init__`](https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/8ddfb34dceeb5dc1ee09b823c3afe5fabfcaa897/zim/gui/widgets.py#L2371,) for example similar to how it is done in [`Dialog._init__`](https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/8ddfb34dceeb5dc1ee09b823c3afe5fabfcaa897/zim/gui/widgets.py#L2815-L2820), by inserting something like:

```
if hasattr(self, 'uistate'):
    assert isinstance(self.uistate, zim.config.ConfigDict) # just to be sure
else:
    self.uistate = zim.config.ConfigDict()
```

**Comment by fmos** [comment] 2022-06-14 12:09
This issue can be solved by merging these two PRs:
- https://github.com/zim-desktop-wiki/zim-desktop-wiki/pull/2085
- https://github.com/shivams/zim-tag-autocompletion/pull/4

**Comment by shivams** [comment] 2022-06-14 18:40
Yep. This works. Thank you @fmos for resolving the issue. I've merged the PR for this plugin, now waiting for the Zim wiki to merge their PR. Meanwhile, you guys can merge the Zim PR locally and continue using the plugin.

**Closed as completed by shivams** 2022-06-14 18:40 UTC
