### ISSUE TITLE
Bug Found: Tag Autocomplete Plugin

### ISSUE THREAD

**Issue by Chucklahoma** [shivams/zim-tag-autocompletion#3] opened 2021-09-26 21:37 UTC
Bug report attached.
[ZimWikiError_FoundWhenAutocompleteWasInitiated.txt](https://github.com/shivams/zim-tag-autocompletion/files/7232301/ZimWikiError_FoundWhenAutocompleteWasInitiated.txt)

**Comment by fmos** [comment] 2022-07-04 09:14
Judging from the attached strack trace, this is a duplicate of #2 and can be closed.

**Closed as completed** 2022-07-04 21:38 UTC
